version: 0.0
os: linux
files:
  - source: awssbdemo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/application/
hooks:
  ApplicationStop:
    - location: ./stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: ./install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: ./start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: ./validate_service.sh
      timeout: 300