version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
      run-as: root
      commands:
        - ls -lart
  build:
    commands:
      - mvn clean install test surefire-report:report -f ./awssbdemo/pom.xml
  post_build:
    commands:
      - echo Entered the post_build phase...
      - ls -lart ./awssbdemo/target/
artifacts:
  files:
    - ./awssbdemo/target/*.jar
    - ./awssbdemo/target/surefire-reports/*.xml
    - ./appspec.yml
  discard-paths: yes
  secondary-artifacts:
      artifact1:
        files:
          - ./scripts/*.sh
        discard-paths: no
cache:
  paths:
    - '/root/.m2/**/*'