version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
      run-as: root
      commands:
        - ls -lart
  build:
    commands:
      - mvn clean install -f ./awssbdemo/pom.xml
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - ./awssbdemo/target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'